# This rule is not used by the project k8s-opreator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to myservice.cyk.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-opreator
    app.kubernetes.io/managed-by: kustomize
  name: apiservice-viewer-role
rules:
- apiGroups:
  - myservice.cyk.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myservice.cyk.io
  resources:
  - apiservices/status
  verbs:
  - get
